import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "./components/Sidebar";
import { MixComp } from "./Elements/SidebarComp";
import { Smile } from "./components/Icons/Smile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-[#62272d] min-h-screen py-4 justify-between`}
      >
        <Sidebar className="h-auto py-2"><MixComp/></Sidebar>
        {children}
        <Sidebar className="h-auto py-2 flex flex-col items-center"><Smile/><MixComp/> </Sidebar>
      </body>
    </html>
  );
}
